# @author Alejandro Galue <agalue@opennms.com>
# Kustomize patch manifest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grafana-helm
        resources:
          $patch: delete

