# @author Alejandro Galue <agalue@opennms.com>
# Kustomize patch manifest

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: shared
spec:
  template:
    spec:
      containers:
      - name: kafka
        env:
        - name: MEM_TOTAL_MB
          $patch: delete
        - name: KAFKA_HEAP_OPTS
          value: -Dcom.sun.management.jmxremote.rmi.port=$(JMX_PORT) -Djava.rmi.server.hostname=$(POD_IP)
        resources:
          $patch: delete

