# @author Alejandro Galue <agalue@opennms.com>
# Kustomize patch manifest

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: shared
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          $patch: delete

