# @author Alejandro Galue <agalue@opennms.com>
# https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onms-share
  labels:
    tier: storage
provisioner: kubernetes.io/azure-file # Alternatively, we could use file.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
- dir_mode=0755
- file_mode=0644
- uid=10001 # OpenNMS User
- gid=10001 # OpenNMS Group
- mfsymlinks
- cache=strict
- actimeo=30
parameters:
  skuName: Standard_LRS
