# @author Alejandro Galue <agalue@opennms.com>
# Default values for opennms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: America/New_York
domain: example.com # The common domain for the Ingress resource.
storageClass: onms-share # The name of the StorageClass that allows ReadWriteMany for RRDs and Core configuration (when using dedicated UI instances).
opennmsVersion: '31.0.1'

# Optionally specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# Example:
# imagePullSecrets:
# - name: customerRegistry
#   dockerServer: registry.k8s.agalue.net
#   dockerUsername: admin
#   dockerPassword: admin
#   dockerEmail: admin@agalue.net

dependencies:

  # A common JKS to white-list all CA certificates for all the dependencies OpenNMS or Sentinel uses.
  truststore:
    content: '' # A base64 encoded content of the JKS Truststore file.
    password: '0p3nNM5'

  # The main OpenNMS database requires PostgreSQL (this is mandatory).
  postgresql:
    hostname: onms-db.shared.svc # IP or FQDN of the external PostgreSQL server
    port: 5432
    username: postgres
    password: P0stgr3s
    sslmode: require # disable, allow, prefer, require, verify-ca, verify-full
    sslfactory: org.postgresql.ssl.LibPQFactory # LibPQFactory, DefaultJavaSSLFactory, NonValidatingFactory
    ca_cert: '' # A base64 encoded content of the CA Certificate

  # The chosen broker technology for the Minion-to-OpenNMS communication (this is mandatory).
  # For TLS with private CA, use the common Truststore.
  kafka:
    hostname: onms-kafka-bootstrap.shared.svc # IP or FQDN of the external Kafka server
    port: 9093
    username: opennms # Pass empty username when using sasl_mechanism=PLAIN
    password: 0p3nNM5 # Pass empty password when using sasl_mechanism=PLAIN
    configuration:
      sasl_mechanism: SCRAM-SHA-512 # PLAIN, SCRAM-SHA-512
      security_protocol: SASL_SSL # PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL

  # Persisting flows requires Elasticsearch
  # For TLS with private CA, use the common Truststore.
  elasticsearch:
    hostname: onms-es-http.shared.svc # IP or FQDN of the external Elasticsearch server
    port: 9200
    username: elastic
    password: 31@st1c
    configuration:
      flows:
        index_strategy: daily
        replication_factor: 0
        num_shards: 1

  # The chosen solution for log aggregation (OpenNMS and Sentinel will forward logs to it via Promtail)
  loki:
    hostname: loki.shared.svc # IP or FQDN of the external Loki server; '' to disable
    username: ''
    password: ''
    ca_cert: '' # A base64 encoded content of the CA Certificate (assumes HTTPS for Loki's URL)
    port: 3100

  # The metrics persistence layer as an alternative to RRDtool.
  cortex:
    # Used only when opennms.configuration.enable_cortex=true
    # See: https://github.com/OpenNMS/opennms-cortex-tss-plugin/blob/master/plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
    writeUrl: http://cortex-distributor.shared.svc.cluster.local:8080/api/v1/push
    readUrl: http://cortex-query-frontend.shared.svc.cluster.local:8080/prometheus/api/v1
    maxConcurrentHttpConnections: 100
    writeTimeoutInMs: 1000
    readTimeoutInMs: 1000
    metricCacheSize: 1000
    externalTagsCacheSize: 1000
    bulkheadMaxWaitDuration: '9223372036854775807' # this is set as a string so it doesn't end up in scientific notation along the way which causes problems later

# The Ingress to expose the OpenNMS and Grafana.
ingress:
  className: nginx
  annotations: {}
  certManager:
    clusterIssuer: opennms-issuer

# OpenNMS Core and UI Instances.
opennms:
  terminationGracePeriodSeconds: 120
  image:
    repository: opennms/horizon
    pullPolicy: IfNotPresent
    tag: '' # Defaults to opennmsVersion
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '2'
      memory: 4Gi
  configuration:
    enable_alec: true    # See alecImage below for how the KAR is retrieved
    enable_cortex: false # See cortexTssImage below for how the KAR is retrieved
    enable_tss_dual_write: false
    enable_acls: false
    rras: # To optionally replace the RRDtool aggregations (pass [] to keep defaults). Affects Pollerd and Collectd
    - RRA:AVERAGE:0.5:1:2016
    - RRA:AVERAGE:0.5:12:1488
    - RRA:AVERAGE:0.5:288:366
    - RRA:MAX:0.5:288:366
    - RRA:MIN:0.5:288:366
    # If alecImage is specified, the KAR is retrieved from the specified Docker image used as an initContainer, otherwise the latest release in GitHub is retrieved
    alecImage: {}
#      repository: opennms/alec
#      pullPolicy: IfNotPresent
#      tag: v2.0.0
    # If cortexTssImage is specified, the KAR is retrieved from the specified Docker image used as an initContainer, otherwise the latest release in GitHub is retrieved
    cortexTssImage: {}
#      repository: opennms/opennms-cortex-tss-plugin
#      pullPolicy: IfNotPresent
#      tag: v2.0.1
    database: # Access to the OpenNMS database
      username: opennms
      password: 0p3nNM5
      pool_size: 50
    storage: # Sizes for RRDs and configuration
      etc: 1Gi # Warning Google Filestore enforces 1TB at a minimum
      rrd: 1000Gi # Depends on how many files you are planning to have (each installation is different)
    http: # Credentials to access the WebUI
      rest_username: opennms # ReST user for Grafana/Helm, Sentinel and Minions (when Twin API is not available)
      rest_password: 0p3nNM5
      admin_password: 0p3nNM5 # Password for the default admin account
  uiServers: # Optional
    replicaCount: 0 # Disabled by default. Requires using ReadWriteMany volumes
    terminationGracePeriodSeconds: 120
    configuration:
      database:
        pool_size: 25
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '2'
        memory: 4Gi
  postConfigJob:
    ttlSecondsAfterFinished: 300

# OpenNMS Sentinel for flow processing (Optional)
sentinel:
  replicaCount: 0 # Use 0 to disable
  terminationGracePeriodSeconds: 60
  image:
    repository: opennms/sentinel
    pullPolicy: IfNotPresent
    tag: '' # Defaults to opennmsVersion
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: '2'
      memory: 2Gi
  configuration:
    database:
      pool_size: 25

# OpenNMS Helm
# Do not use Grafana images, or you'd have to manually install the Helm Plugin from Github every time the container starts.
grafana:
  replicaCount: 2
  image:
    repository: opennms/helm
    pullPolicy: IfNotPresent
    tag: '7.2.0'
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configuration:
    ui:
      admin_password: 0p3nNM5 # Default password for the admin account
    database: # Assumes PostgreSQL
      username: grafana
      password: Gr@f@n@
      sslmode: require # disable, require, verify-full
      image: # For the initialization container to create the database
        repository: postgres
        pullPolicy: IfNotPresent
        tag: '12'
  imageRenderer: # Required to generate PDF reports from OpenNMS
    replicaCount: 2
    image:
      repository: grafana/grafana-image-renderer
      pullPolicy: IfNotPresent
      tag: latest
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Log aggregator configured as a sidecar for OpenNMS and Sentinel
promtail:
  image:
    repository: grafana/promtail
    pullPolicy: IfNotPresent
    tag: latest
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
