# @author Alejandro Galue <agalue@opennms.com>
# Default values for opennms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: America/New_York
domain: example.com
storageClass: onms-share
opennmsVersion: '29.0.1'
imagePullSecrets: []

dependencies:
  truststore:
    content: '' # A base64 encoded content of the JKS Truststore file.
    password: '0p3nNM5'
  kafka:
    hostname: onms-kafka-bootstrap.shared.svc
    port: 9092
    username: opennms
    password: 0p3nNM5
    configuration:
      sasl_mechanism: SCRAM-SHA-512
      security_protocol: SASL_SSL
  elasticsearch:
    hostname: onms-es-http.shared.svc
    port: 9200
    username: elastic
    password: 31@st1c
    configuration:
      flows:
        index_strategy: daily
        replication_factor: 0
        num_shards: 1
  postgresql:
    hostname: onms-db.shared.svc
    port: 5432
    username: postgres
    password: P0stgr3s
    sslmode: require # disable, allow, prefer, require, verify-ca, verify-full
    sslfactory: org.postgresql.ssl.LibPQFactory # LibPQFactory, DefaultJavaSSLFactory, NonValidatingFactory
    ca_cert: '' # A base64 encoded content of the Server Certificate

ingress:
  className: nginx
  certManager:
    clusterIssuer: opennms-issuer

opennms:
  image:
    repository: opennms/horizon
    pullPolicy: IfNotPresent
    tag: '' # Defaults to opennmsVersion
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '2'
      memory: 4Gi
  configuration:
    enable_alec: true
    enable_acls: false
    database:
      username: opennms
      password: 0p3nNM5
      pool_size: 50
    storage:
      etc: 1Gi
      rrd: 1000Gi
  uiServers:
    replicaCount: 2
    configuration:
      database:
        pool_size: 25
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '2'
        memory: 4Gi

sentinel:
  replicaCount: 2
  image:
    repository: opennms/sentinel
    pullPolicy: IfNotPresent
    tag: '' # Defaults to opennmsVersion
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: '2'
      memory: 2Gi
  configuration:
    database:
      pool_size: 25
    opennms:
      http_username: admin
      http_password: admin

grafana:
  replicaCount: 2
  image:
    repository: opennms/helm
    pullPolicy: IfNotPresent
    tag: '7.2.0'
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configuration:
    database: # Assumes PostgreSQL
      username: grafana
      password: Gr@f@n@
      sslmode: require # disable, require, verify-full
    ui:
      admin_password: 0p3nNM5
    opennms: # Access to the OpenNMS UI for Helm datasources
      http_username: admin
      http_password: admin
  imageRenderer:
    replicaCount: 2
    image:
      repository: grafana/grafana-image-renderer
      pullPolicy: IfNotPresent
      tag: latest
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
