# @author Alejandro Galue <agalue@opennms.com>
# Default values for opennms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: America/New_York
domain: example.com
storageClass: onms-share
opennmsVersion: '29.0.1'

# Optionally specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# Example:
# imagePullSecrets:
# - name: customerRegistry
#   dockerServer: registry.k8s.agalue.net
#   dockerUsername: admin
#   dockerPassword: admin
#   dockerEmail: admin@agalue.net

dependencies:
  truststore:
    content: '' # A base64 encoded content of the JKS Truststore file.
    password: '0p3nNM5'
  loki:
    hostname: onms-loki.shared.svc
    port: 3100
    promtail:
      repository: grafana/promtail
      pullPolicy: IfNotPresent
      tag: latest
  kafka:
    hostname: onms-kafka-bootstrap.shared.svc
    port: 9092
    username: opennms
    password: 0p3nNM5
    configuration:
      sasl_mechanism: SCRAM-SHA-512
      security_protocol: SASL_SSL
  elasticsearch:
    hostname: onms-es-http.shared.svc
    port: 9200
    username: elastic
    password: 31@st1c
    configuration:
      flows:
        index_strategy: daily
        replication_factor: 0
        num_shards: 1
  postgresql:
    hostname: onms-db.shared.svc
    port: 5432
    username: postgres
    password: P0stgr3s
    sslmode: require # disable, allow, prefer, require, verify-ca, verify-full
    sslfactory: org.postgresql.ssl.LibPQFactory # LibPQFactory, DefaultJavaSSLFactory, NonValidatingFactory
    ca_cert: '' # A base64 encoded content of the Server Certificate
  cortex: # Not production ready - use for test/dev purposes only
    baseUrl: '' # Used only when opennms.enable_cortex=true

ingress:
  className: nginx
  annotations: {}
  certManager:
    clusterIssuer: opennms-issuer

# OpenNMS Core and UI
opennms:
  terminationGracePeriodSeconds: 120
  image:
    repository: opennms/horizon
    pullPolicy: IfNotPresent
    tag: '' # Defaults to opennmsVersion
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '2'
      memory: 4Gi
  configuration:
    enable_alec: true    # Downloads KAR from Github when the container starts if it doesn't exist on the image
    enable_cortex: false # Downloads KAR from Github when the container starts if it doesn't exist on the image
    enable_acls: false
    rras: # Affects Pollerd and Collectd
    - RRA:AVERAGE:0.5:1:4032
    - RRA:AVERAGE:0.5:12:1488
    - RRA:AVERAGE:0.5:288:366
    - RRA:MAX:0.5:288:366
    - RRA:MIN:0.5:288:366
    database:
      username: opennms
      password: 0p3nNM5
      pool_size: 50
    storage:
      etc: 1Gi
      rrd: 1000Gi
    http:
      rest_username: opennms
      rest_password: 0p3nNM5
      admin_password: 0p3nNM5
  uiServers:
    replicaCount: 2
    terminationGracePeriodSeconds: 120
    configuration:
      database:
        pool_size: 25
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '2'
        memory: 4Gi

# OpenNMS Sentinel
sentinel:
  replicaCount: 2
  terminationGracePeriodSeconds: 60
  image:
    repository: opennms/sentinel
    pullPolicy: IfNotPresent
    tag: '' # Defaults to opennmsVersion
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: '2'
      memory: 2Gi
  configuration:
    database:
      pool_size: 25

# OpenNMS Helm
grafana:
  replicaCount: 2
  image:
    repository: opennms/helm
    pullPolicy: IfNotPresent
    tag: '7.2.0'
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configuration:
    database: # Assumes PostgreSQL
      username: grafana
      password: Gr@f@n@
      sslmode: require # disable, require, verify-full
    ui:
      admin_password: 0p3nNM5
  imageRenderer: # Required to generate PDF reports from OpeNNMS
    replicaCount: 2
    image:
      repository: grafana/grafana-image-renderer
      pullPolicy: IfNotPresent
      tag: latest
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
