# @author Alejandro Galue <agalue@opennms.com>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onms-core
  namespace: opennms
  labels:
    app: onms-core
spec:
  serviceName: onms-core
  replicas: 1 # DO NOT CHANGE. The solution only allows 1 instance
  selector:
    matchLabels:
      app: onms-core
  template:
    metadata:
      labels:
        app: onms-core
    spec:
      terminationGracePeriodSeconds: 120
      securityContext: # To write data as non-root on the volumes
        fsGroup: 10001 # Default opennms user
      initContainers:
      # Initializes/Updates OpenNMS Configuration
      # Requires the same image/version used at runtime
      - name: init
        image: opennms/horizon:29.0.1
        imagePullPolicy: IfNotPresent
        command: [ bash, /init.sh ]
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        volumeMounts:
        - name: etc
          mountPath: /opennms-etc
        - name: scripts
          mountPath: /init.sh
          subPath: onms-core-init.sh
      containers:
      - name: onms
        image: opennms/horizon:29.0.1
        imagePullPolicy: IfNotPresent
        args:
        - -s
        ports:
        - containerPort: 8101
          name: karaf
        - containerPort: 8980
          name: http
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        env:
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS # Alternative to opennms.conf
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+UseStringDeduplication
        volumeMounts:
        - name: etc
          mountPath: /opt/opennms/etc
        - name: rrd
          mountPath: /opennms-data/rrd
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: '2'
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: scripts
        configMap:
          name: app-scripts
      - name: etc
        persistentVolumeClaim:
          claimName: onms-etc-pvc
          readOnly: false
      - name: rrd
        persistentVolumeClaim:
          claimName: onms-rrd-pvc
          readOnly: false
