# @author Alejandro Galue <agalue@opennms.com>
#
# WARNING: For testing purposes only

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: onms
spec:
  version: 7.6.2 # Must match an available OpenNMS Plugin version
  nodeSets:
  - name: default
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: onms-plugin
          image: busybox
          command: [ sh, -c ]
          args: [ "wget $(PLUGIN_URL) && unzip -o elasticsearch-drift-plugin-$(PLUGIN_VERSION).zip -d /plugin/" ]
          env:
            - name: PLUGIN_VERSION # Must match the chosen Elasticsearch version
              value: '7.6.2'
            - name: PLUGIN_URL
              value: https://github.com/OpenNMS/elasticsearch-drift-plugin/releases/download/v$(PLUGIN_VERSION)/elasticsearch-drift-plugin-$(PLUGIN_VERSION).zip
          volumeMounts:
          - name: onms-plugin-dir
            mountPath: /plugin
        containers:
        - name: elasticsearch
          volumeMounts:
          - name: onms-plugin-dir
            mountPath: /usr/share/elasticsearch/plugins/drift
        volumes:
        - name: onms-plugin-dir
          emptyDir: {}
