# @author Alejandro Galue <agalue@opennms.com>
#
# WARNING: For testing purposes only

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elastic
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
  selector:
    app: elastic

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  serviceName: elasticsearch
  replicas: 1 # The solution only allows 1 instance
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: onms-plugin
        image: busybox
        command: [ sh, -c ]
        args: [ "wget $(PLUGIN_URL) && unzip elasticsearch-drift-plugin-$(PLUGIN_VERSION).zip -d /plugin/" ]
        env:
          - name: PLUGIN_VERSION # Must match the chosen Elasticsearch version
            value: '7.6.2'
          - name: PLUGIN_URL
            value: https://github.com/OpenNMS/elasticsearch-drift-plugin/releases/download/v$(PLUGIN_VERSION)/elasticsearch-drift-plugin-$(PLUGIN_VERSION).zip
        volumeMounts:
        - name: onms-plugin-dir
          mountPath: /plugin
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2 # Must match PLUGIN_VERSION
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: TZ
          value: America/New_York # Should match app-settings from k8s/kustomization.yaml
        - name: cluster.name
          value: OpenNMS
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.type
          value: single-node
        - name: xpack.monitoring.collection.enabled
          value: 'true'
        - name: search.max_buckets # To avoid "Too many buckets exception" in Grafana
          value: '50000'
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: ES_JAVA_OPTS # TODO jvm.options default will be used if Xms/Xmx are not passed
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m
        - name: ELASTIC_PASSWORD
          value: 31@st1c # Must match app-credentials from k8s/kustomization.yaml
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: onms-plugin-dir
          mountPath: /usr/share/elasticsearch/plugins/drift
        resources:
          limits:
            cpu: 400m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: onms-plugin-dir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
