# @author Alejandro Galue <agalue@opennms.com>
#
# WARNING: For testing purposes only

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: opennms # Must match KAFKA_SASL_USERNAME from app-credentials
  labels:
    strimzi.io/cluster: onms
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: kafka-user-credentials
          key: opennms

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: onms
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
      authentication:
        type: scram-sha-512
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          alternativeNames: # Based on the ExternalName service that OpenNMS would use
          - kafka.apex1.svc.cluster.local
          - kafka.apex1.svc
          - kafka.apex1
    - name: external
      port: 9094
      type: ingress
      tls: true
      authentication:
        type: scram-sha-512
      configuration:
        class: nginx
        bootstrap:
          host: kafka.k8s.agalue.net
        brokers:
        - broker: 0
          host: kafka-0.k8s.agalue.net
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

