# @author Alejandro Galue <agalue@opennms.com>
#
# WARNING: For testing purposes only

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onms-db
spec:
  secretName: onms-db-certs
  dnsNames:
  - onms-db
  - onms-db.shared
  - onms-db.shared.svc
  - onms-db.shared.svc.cluster.local
  issuerRef:
    name: opennms-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: onms-db
spec:
  teamId: onms
  volume:
    size: 100Gi
  numberOfInstances: 1
  users:
    opennms:
    - superuser
    - createdb
  postgresql:
    version: "13"
  spiloFSGroup: 103
  patroni:
    initdb:
      encoding: UTF8
      locale: en_US.UTF-8
      data-checksums: "true"
    pg_hba:
    - local     all         all                     trust
    - hostssl   all         +zalandos 127.0.0.1/32  pam
    - host      all         all       127.0.0.1/32  md5
    - hostssl   all         +zalandos ::1/128       pam
    - host      all         all       ::1/128       md5
    - local     replication standby                 trust
    - hostssl   replication standby   all           md5
    - hostnossl all         all       all           md5 # Until we find a proper solution for all clients
    - hostssl   all         +zalandos all           pam
    - hostssl   all         all       all           md5
  tls:
    secretName: onms-db-certs
