# @author Alejandro Galue <agalue@opennms.com>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-truststores
  namespace: {{ .Release.Name }}
binaryData:
  {{- if .Values.dependencies.kafka.truststore.content }}
  kafka.jks: |
    {{ .Values.dependencies.kafka.truststore.content }}
  {{- end }}
  {{- if .Values.dependencies.elasticsearch.truststore.content }}
  elasticsearch.jks: |
    {{ .Values.dependencies.elasticsearch.truststore.content }}
  {{- end }}
  {{- if .Values.dependencies.postgresql.truststore.content }}
  postgresql.jks: |
    {{ .Values.dependencies.postgresql.truststore.content }}
  {{- end }}
