{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-jks
  namespace: {{ .Release.Name }}
  labels:
    {{- include "opennms.labels" . | nindent 4 }}
data: # To be mounted at /etc/java/jks
  {{- if .Values.dependencies.truststore.content }}
  truststore.jks: |
    {{ .Values.dependencies.truststore.content }}
  {{- end }}
  {{- if .Values.dependencies.postgresql.ca_cert }}
  postgresql-ca.cert: |
    {{ .Values.dependencies.postgresql.ca_cert }}
  {{- end }}
