{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-scripts
  namespace: {{ .Release.Name }}
data:
  grafana-init.sh: |
    {{- .Files.Get "scripts/grafana-init.sh" | nindent 4 }}
  onms-core-init.sh: |
    {{- .Files.Get "scripts/onms-core-init.sh" | nindent 4 }}
  onms-sentinel-init.sh: |
    {{- .Files.Get "scripts/onms-sentinel-init.sh" | nindent 4 }}
  onms-ui-init.sh: |
    {{- .Files.Get "scripts/onms-ui-init.sh" | nindent 4 }}
