{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
  namespace: {{ .Release.Name }}
  labels:
    {{- include "opennms.labels" . | nindent 4 }}
data:
  TZ: {{ .Values.timezone | quote }}
  DOMAIN: {{ include "opennms.domain" . | quote }}
  POSTGRES_HOST: {{ .Values.dependencies.postgresql.hostname | quote }}
  POSTGRES_PORT: {{ .Values.dependencies.postgresql.port | quote }}
  POSTGRES_SSL_MODE: {{ .Values.dependencies.postgresql.sslmode | quote }}
  POSTGRES_SSL_FACTORY: {{ .Values.dependencies.postgresql.sslfactory | quote }}
  ENABLE_ALEC: {{ ((.Values.opennms).configuration).enable_alec | default "false" | quote }}
  ENABLE_ACLS: {{ ((.Values.opennms).configuration).enable_acls | default "false" | quote }}
  ENABLE_TELEMETRYD: {{ if gt ((.Values.sentinel).replicaCount|int) 0 }}"true"{{ else }}"false"{{ end }}
  ENABLE_CORTEX: {{ ((.Values.opennms).configuration).enable_cortex | quote }}
  ENABLE_TSS_DUAL_WRITE: {{ ((.Values.opennms).configuration).enable_tss_dual_write | quote }}
  ENABLE_GRAFANA: {{ if gt ((.Values.grafana).replicaCount|int) 0 }}"true"{{ else }}"false"{{ end }}
  OPENNMS_INSTANCE_ID: {{ .Release.Name | quote }}
  OPENNMS_SERVER: {{ printf "onms-core.%s.svc" .Release.Name | quote }}
  OPENNMS_DBNAME: {{ printf "%s_opennms" .Release.Name | quote }}
  {{- if ((.Values.opennms).configuration).rras }}
  OPENNMS_RRAS: {{ join ";" .Values.opennms.configuration.rras }}
  {{- end }}
  {{- if ((.Values.opennms).configuration).enable_cortex }}
  CORTEX_WRITE_URL: {{ .Values.dependencies.cortex.writeUrl | quote }}
  CORTEX_READ_URL: {{ .Values.dependencies.cortex.readUrl | quote }}
  CORTEX_MAX_CONCURRENT_HTTP_CONNECTIONS: {{ .Values.dependencies.cortex.maxConcurrentHttpConnections | quote }}
  CORTEX_WRITE_TIMEOUT: {{ .Values.dependencies.cortex.writeTimeoutInMs | quote }}
  CORTEX_READ_TIMEOUT: {{ .Values.dependencies.cortex.readTimeoutInMs | quote }}
  CORTEX_METRIC_CACHE_SIZE: {{ .Values.dependencies.cortex.metricCacheSize | quote }}
  CORTEX_EXTERNAL_TAGS_CACHE_SIZE: {{ .Values.dependencies.cortex.externalTagsCacheSize | quote }}
  CORTEX_BULKHEAD_MAX_WAIT_DURATION: {{ .Values.dependencies.cortex.bulkheadMaxWaitDuration | quote }}
  {{- end }}
  {{- if ((.Values.dependencies).elasticsearch).hostname }}
  ELASTICSEARCH_SERVER: {{ printf "%s:%d" .Values.dependencies.elasticsearch.hostname (.Values.dependencies.elasticsearch.port | int) | quote }}
  ELASTICSEARCH_INDEX_STRATEGY_FLOWS: {{ .Values.dependencies.elasticsearch.configuration.flows.index_strategy | quote }}
  ELASTICSEARCH_REPLICATION_FACTOR: {{ .Values.dependencies.elasticsearch.configuration.flows.replication_factor | quote }}
  ELASTICSEARCH_NUM_SHARDS: {{ .Values.dependencies.elasticsearch.configuration.flows.num_shards | quote }}
  {{- end }}
  {{- if ((.Values.dependencies).kafka).hostname }}
  KAFKA_BOOTSTRAP_SERVER: {{ printf "%s:%d" .Values.dependencies.kafka.hostname (.Values.dependencies.kafka.port | default "9092" | int) | quote }}
  KAFKA_SASL_MECHANISM: {{ .Values.dependencies.kafka.configuration.sasl_mechanism | quote }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.dependencies.kafka.configuration.security_protocol | quote }}
  {{- end }}
  GRAFANA_SERVER: {{ printf "grafana.%s.svc" .Release.Name | quote }}
  GF_SERVER_DOMAIN: {{ printf "grafana.%s" (include "opennms.domain" .) | quote }} # Should match FQDN on the Ingress
  GF_SERVER_ROOT_URL: "/"
  GF_DATABASE_TYPE: "postgres"
  GF_DATABASE_NAME: {{ printf "%s_grafana" .Release.Name | quote }}
  GF_DATABASE_SSL_MODE: {{ (((.Values.grafana).configuration).database).sslmode | default "disable" | quote }}
  GF_DATABASE_CA_CERT_PATH: "/etc/java/jks/postgresql-ca.crt"
  GF_SESSION_PROVIDER: "postgres"
