{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

{{- $namespace := .Release.Name }}
{{- range $k, $r := .Values.imagePullSecrets }}
{{- $json := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $r.dockerServer $r.dockerUsername $r.dockerPassword $r.dockerEmail (printf "%s:%s" $r.dockerUsername $r.dockerPassword | b64enc) }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ $r.name }}
  namespace: {{ $namespace }}
data:
  .dockerconfigjson: {{ $json | b64enc }}
{{- end }}
