{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

{{- if gt ((.Values.grafana).replicaCount|int) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Name }}
  labels:
    app: grafana
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: grafana
    {{- include "opennms.selectorLabels" . | nindent 4 }}
{{- end }}
