{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

{{- if ((.Values.dependencies).loki).hostname }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Release.Name }}
  labels:
    {{- include "opennms.labels" . | nindent 4 }}
data:
  promtail.onms_core.config.yaml: |
    {{- include "opennms.promtailBaseConfig" . | nindent 4 }}
        labels:
          job: opennms_core
          __path__: /opt/opennms/logs/*.log
  promtail.onms_ui.config.yaml: |
    {{- include "opennms.promtailBaseConfig" . | nindent 4 }}
        labels:
          job: opennms_ui
          __path__: /opt/opennms/logs/*.log
  promtail.sentinel.config.yaml: |
    {{- include "opennms.promtailBaseConfig" . | nindent 4 }}
        labels:
          job: opennms_sentinel
          __path__: /opt/sentinel/data/log/karaf.log
{{- end }}
