{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-renderer
  namespace: {{ .Release.Name }}
  labels:
    app: grafana-renderer
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grafana.imageRenderer.replicaCount }} 
  selector:
    matchLabels:
      app: grafana-renderer
      {{- include "opennms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: grafana-renderer
        {{- include "opennms.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $k, $r := .Values.imagePullSecrets }}
        - name: {{ $r.name }}
        {{- end }}
      {{- end }}
      containers:
      - name: grafana-renderer
        image: {{ printf "%s:%s" .Values.grafana.imageRenderer.image.repository .Values.grafana.imageRenderer.image.tag }}
        imagePullPolicy: {{ .Values.grafana.imageRenderer.image.imagePullPolicy }}
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: BROWSER_TZ
          value: {{ .Values.timezone }}
        - name: ENABLE_METRICS
          value: 'true'
        {{- with .Values.grafana.imageRenderer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
