{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Name }}
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: grafana