{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-config
  namespace: {{ .Release.Name }}
data:
  plugins.helm.yaml: |
    apiVersion: 1
    apps:
    - type: opennms-helm-app
      disabled: false
  datasources.helm.yaml: |
    apiVersion: 1
    datasources:
    - name: OpenNMS-Performance
      type: opennms-helm-performance-datasource
      isDefault: true
      editable: true
      access: proxy
      url: http://onms-ui.{{ .Release.Name }}:8980/opennms
      basicAuth: true
      basicAuthUser: {{ .Values.grafana.configuration.opennms.http_username }}
      secureJsonData:
        basicAuthPassword: {{ .Values.grafana.configuration.opennms.http_password }}
    - name: OpenNMS-Entity
      type: opennms-helm-entity-datasource
      editable: true
      access: proxy
      url: http://onms-ui.{{ .Release.Name }}:8980/opennms
      basicAuth: true
      basicAuthUser: {{ .Values.grafana.configuration.opennms.http_username }}
      secureJsonData:
        basicAuthPassword: {{ .Values.grafana.configuration.opennms.http_password }}
    - name: OpenNMS-Flow
      type: opennms-helm-flow-datasource
      editable: true
      access: proxy
      url: http://onms-ui.{{ .Release.Name }}:8980/opennms
      basicAuth: true
      basicAuthUser: {{ .Values.grafana.configuration.opennms.http_username }}
      secureJsonData:
        basicAuthPassword: {{ .Values.grafana.configuration.opennms.http_password }}
