{{- /* @author Alejandro Galue <agalue@opennms.com> */}}
{{- $domain := printf "%s.%s" .Release.Name .Values.domain -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: {{ .Release.Name }}
  labels:
    {{- include "opennms.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: route
    ingress.kubernetes.io/session-cookie-hash: sha1
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- if ((.Values.ingress).certManager).clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: onms-ingress-cert
      hosts:
        {{- if gt ((.Values.opennms).uiServers).replicaCount 0.0 }}
        - onms.{{ $domain }}
        {{- end }}
        - onms-core.{{ $domain }}
        - grafana.{{ $domain }}
  rules:
    {{- if gt ((.Values.opennms).uiServers).replicaCount 0.0 }}
    - host: onms.{{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onms-ui
                port:
                  number: 8980
          - path: /opennms/nrt
            pathType: Prefix
            backend:
              service:
                name: onms-core
                port:
                  number: 8980
    {{- end }}
    - host: onms-core.{{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onms-core
                port:
                  number: 8980
    - host: grafana.{{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
