# @author Alejandro Galue <agalue@opennms.com>
#
# WARNING: Ensure the usage of correct host domains and cert-manager issuer.

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: {{ .Release.Name }}
  annotations:
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: route
    ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: onms-ingress-cert
      hosts:
        - onms.{{ .Release.Name }}.{{ .Values.domain }}
        - onms-core.{{ .Release.Name }}.{{ .Values.domain }}
        - grafana.{{ .Release.Name }}.{{ .Values.domain }}
  rules:
    - host: onms.{{ .Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onms-ui
                port:
                  number: 8980
          - path: /opennms/nrt
            pathType: Prefix
            backend:
              service:
                name: onms-core
                port:
                  number: 8980
    - host: onms-core.{{ .Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onms-core
                port:
                  number: 8980
    - host: grafana.{{ .Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
