{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onms-ui
  namespace: {{ .Release.Name }}
  labels:
    app: onms-ui
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opennms.uiServers.replicaCount }}
  selector:
    matchLabels:
      app: onms-ui
      {{- include "opennms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: onms-ui
        {{- include "opennms.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 120
      initContainers:
      # Initializes OpenNMS Configuration
      # Requires the same image/version used at runtime
      - name: init
        image: {{ .Values.opennms.image.repository }}:{{ .Values.opennms.image.tag | default .Values.opennmsVersion }}
        imagePullPolicy: {{ .Values.opennms.image.imagePullPolicy }}
        command: [ bash, /init.sh ]
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        volumeMounts:
        - name: overlay
          mountPath: /opt/opennms-overlay
        - name: scripts
          mountPath: /init.sh
          subPath: onms-ui-init.sh
      containers:
      - name: onms
        image: {{ .Values.opennms.image.repository }}:{{ .Values.opennms.image.tag | default .Values.opennmsVersion }}
        imagePullPolicy: {{ .Values.opennms.image.imagePullPolicy }}
        args:
        - -s
        ports:
        - containerPort: 8101
          name: karaf
        - containerPort: 8980
          name: http
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        volumeMounts:
        - name: rrd-core
          mountPath: /opennms-data/rrd
        - name: etc-core
          mountPath: /opennms-core/etc # Must match CORE_CONFIG_DIR from onms-ui-init.sh
        - name: overlay
          mountPath: /opt/opennms-overlay
        - name: jks
          mountPath: /etc/java/jks
        env:
        - name: OPENNMS_DATABASE_CONNECTION_MAXPOOL
          value: {{ .Values.opennms.uiServers.configuration.database.pool_size | default "50" | quote }}
        {{- $opt :=  include "opennms.jvmOptions" . }}
        {{- if .Values.opennms.uiServers.resources }}
        {{- with .Values.opennms.uiServers.resources }}
        {{- if ((.requests).memory) }}
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m {{ $opt }}
        {{- end }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        - name: JAVA_OPTS
          value: {{ $opt }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: overlay
        emptyDir: {}
      - name: scripts
        configMap:
          name: app-scripts
      - name: jks
        configMap:
          name: app-jks
      - name: etc-core
        persistentVolumeClaim:
          claimName: onms-etc-pvc
          readOnly: true
      - name: rrd-core
        persistentVolumeClaim:
          claimName: onms-rrd-pvc
          readOnly: true
