{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

{{- $image := printf "%s:%s" .Values.opennms.image.repository (.Values.opennms.image.tag | default .Values.opennmsVersion) -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onms-core
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  serviceName: onms-core
  replicas: 1 # DO NOT CHANGE. The solution only allows 1 instance
  selector:
    matchLabels:
      app: onms-core
      {{- include "opennms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: onms-core
        {{- include "opennms.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 10001 # Required for Google Fileshare (might impact performance)
      terminationGracePeriodSeconds: {{ .Values.opennms.terminationGracePeriodSeconds | default 120 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $k, $r := .Values.imagePullSecrets }}
        - name: {{ $r.name }}
        {{- end }}
      {{- end }}
      initContainers:
      {{- if and (.Values.opennms.configuration.enable_alec) (.Values.opennms.configuration.alecImage) }}
      - name: alec-kar
        image: {{ .Values.opennms.configuration.alecImage.repository }}:{{ .Values.opennms.configuration.alecImage.tag }}
        imagePullPolicy: {{ .Values.opennms.configuration.alecImage.imagePullPolicy }}
        command: [ cp, /plugins/opennms-alec-plugin.kar, /opennms-deploy ]
        securityContext: # To guarantee ownership of the KAR file so that OpenNMS won't complain.
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: deploy
          mountPath: /opennms-deploy # Required by the init script - DEPLOY_DIR
      {{- end }}
      {{- if and (.Values.opennms.configuration.enable_cortex) (.Values.opennms.configuration.cortexTssImage) }}
      - name: cortex-tss-kar
        image: {{ .Values.opennms.configuration.cortexTssImage.repository }}:{{ .Values.opennms.configuration.cortexTssImage.tag }}
        imagePullPolicy: {{ .Values.opennms.configuration.cortexTssImage.imagePullPolicy }}
        command: [ cp, /plugins/opennms-cortex-tss-plugin.kar, /opennms-deploy ]
        securityContext: # To guarantee ownership of the KAR file so that OpenNMS won't complain.
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: deploy
          mountPath: /opennms-deploy # Required by the init script - DEPLOY_DIR
      {{- end }}
      # Initializes/Updates OpenNMS Configuration
      # Requires the same image/version used at runtime
      - name: init
        image: {{ $image }}
        imagePullPolicy: {{ .Values.opennms.image.imagePullPolicy }}
        command: [ bash, /scripts/onms-core-init.sh ]
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        env:
        - name: OPENNMS_DATABASE_CONNECTION_MAXPOOL
          value: {{ .Values.opennms.configuration.database.pool_size | default "50" | quote }}
        volumeMounts:
        - name: etc
          mountPath: /opennms-etc # Required by the script - CONFIG_DIR
        - name: deploy
          mountPath: /opennms-deploy # Required by the script - DEPLOY_DIR
        - name: overlay
          mountPath: /opt/opennms-overlay # Required by the script - OVERLAY_DIR
        - name: scripts
          mountPath: /scripts # Required by the script
      containers:
      - name: onms
        image: {{ $image }}
        imagePullPolicy: {{ .Values.opennms.image.imagePullPolicy }}
        args:
        - -s
        ports:
        - containerPort: 8101
          name: karaf
        - containerPort: 8980
          name: http
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        volumeMounts:
        {{- if (include "opennms.enable_tss_rrd" .) }}
        - name: rrd
          mountPath: /opennms-data/rrd
        {{- end }}
        - name: etc
          mountPath: /opt/opennms/etc
        - name: deploy
          mountPath: /opt/opennms/deploy
        - name: logs
          mountPath: /opt/opennms/logs
        - name: overlay
          mountPath: /opt/opennms-overlay
        - name: jks
          mountPath: /etc/java/jks
        - name: jks
          mountPath: /opt/opennms/.postgresql/root.crt
          subPath: postgresql-ca.crt
        env:
        {{- $opt :=  include "opennms.jvmOptions" . }}
        {{- if .Values.opennms.resources }}
        {{- with .Values.opennms.resources }}
        {{- if ((.requests).memory) }}
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m {{ $opt }}
        {{- end }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        - name: JAVA_OPTS
          value: {{ $opt }}
        {{- end }}
        startupProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          failureThreshold: 30
          periodSeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          periodSeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          periodSeconds: 60
          timeoutSeconds: 5
      {{- if ((.Values.dependencies).loki).hostname }}
      - name: promtail
        image: {{ printf "%s:%s" .Values.promtail.image.repository (.Values.promtail.image.tag | default "latest") }}
        imagePullPolicy: {{ .Values.promtail.image.pullPolicy }}
        args:
        - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: logs
          mountPath: /opt/opennms/logs
        - name: jks
          mountPath: /etc/jks
        - name: promtail
          mountPath: /etc/promtail/promtail.yaml
          subPath: promtail.onms_core.config.yaml
        {{- with .Values.promtail.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      - name: deploy
        emptyDir: {}
      - name: overlay
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: scripts
        configMap:
          name: app-scripts
      {{- if ((.Values.dependencies).loki).hostname }}
      - name: promtail
        configMap:
          name: promtail-config
      {{- end }}
      - name: jks
        secret:
          secretName: app-jks
      - name: etc
        persistentVolumeClaim:
          claimName: onms-etc-pvc
          readOnly: false
      {{- if (include "opennms.enable_tss_rrd" .) }}
      - name: rrd
        persistentVolumeClaim:
          claimName: onms-rrd-pvc
          readOnly: false
      {{- end }}
