{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

{{- if gt (((.Values).opennms).uiServers).replicaCount 0.0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: onms-ui
  namespace: {{ .Release.Name }}
  labels:
    app: onms-ui
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 8980
    name: http
  - port: 8101
    name: karaf
  selector:
    app: onms-ui
    {{- include "opennms.selectorLabels" . | nindent 4 }}
{{- end }}