{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: onms-post-config
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ (.Values.opennms.postConfigJob.ttlSecondsAfterFinished | default "300") }}
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: {{ printf "%s:%s" .Values.opennms.image.repository (.Values.opennms.image.tag | default .Values.opennmsVersion) }}
        imagePullPolicy: IfNotPresent
        command: [ bash, /scripts/onms-post-init.sh ]
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: app-scripts
