{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onms-etc-pvc
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    tier: storage
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  storageClassName: {{ required "A ReadWriteMany StorageClass is required!" .Values.storageClass }}
  accessModes:
  - ReadWriteMany # Mandatory
  resources:
    requests:
      storage: {{ .Values.opennms.configuration.storage.etc | default "1Gi" }}
