{{- /* @author Alejandro Galue <agalue@opennms.com> */}}

{{- if .Values.opennms.configuration.storage.mibs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onms-mibs-pvc
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    tier: storage
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  {{- if gt (((.Values.opennms).uiServers).replicaCount|int) 0 }}
  storageClassName: {{ required "A ReadWriteMany StorageClass is required!" .Values.storageClass }}
  accessModes:
  - ReadWriteMany # Mandatory
  {{- else }}
  accessModes: # Assumes default StorageClass
  - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.opennms.configuration.storage.mibs }}
{{- end }}
