# @author Alejandro Galue <agalue@opennms.com>

---
apiVersion: v1
kind: Service
metadata:
  name: onms-ui
  namespace: {{ .Release.Name }}
  labels:
    app: onms-ui
spec:
  clusterIP: None
  ports:
  - port: 8980
    name: http
  - port: 8101
    name: karaf
  selector:
    app: onms-ui