# @author Alejandro Galue <agalue@opennms.com>
#
# WARNING: For testing purposes only

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minion-config
  namespace: opennms
data:
  # Must match Must match app-settings and app-credentials from k8s/kustomization.yaml
  minion-config.yaml: |
    id: minion-0
    location: Minikube
    system:
      properties:
        org.opennms.instance.id: onms
    ipc:
      twin:
        kafka:
          bootstrap.servers: kafka.opennms:9093
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="opennms" password="0p3nNM5";
          ssl.truststore.location: /opt/minion/etc/kafka-truststore.jks
          ssl.truststore.password: 0p3nNM5
      rpc:
        kafka:
          bootstrap.servers: kafka.opennms:9093
          single-topic: true
          request.timeout.ms: 30000
          max.concurrent.calls: 10000
          acks: 0
          linger.ms: 5
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="opennms" password="0p3nNM5";
          ssl.truststore.location: /opt/minion/etc/kafka-truststore.jks
          ssl.truststore.password: 0p3nNM5
      sink:
        kafka:
          bootstrap.servers: kafka.opennms:9093
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="opennms" password="0p3nNM5";
          ssl.truststore.location: /opt/minion/etc/kafka-truststore.jks
          ssl.truststore.password: 0p3nNM5

---
apiVersion: v1
kind: Service
metadata:
  name: minion
  namespace: opennms
  labels:
    app: minion
spec:
  clusterIP: None
  ports:
  - name: karaf
    protocol: TCP
    port: 8201
    targetPort: karaf
  - name: http
    protocol: TCP
    port: 8181
    targetPort: http
  - name: traps
    protocol: UDP
    port: 1162
    targetPort: traps
  - name: syslog
    protocol: UDP
    port: 1514
    targetPort: syslog
  selector:
    app: minion

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minion
  namespace: opennms
  labels:
    app: minion
spec:
  serviceName: minion
  replicas: 1 # Do not change
  selector:
    matchLabels:
      app: minion
  template:
    metadata:
      labels:
        app: minion
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: onms-core.opennms:8980
        - name: TIMEOUT
          value: '900'
      containers:
      - name: minion
        image: opennms/minion:29.0.1
        imagePullPolicy: IfNotPresent
        args:
        - -c
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: app-settings
        ports:
        - containerPort: 1162
          protocol: UDP
          name: traps
        - containerPort: 1514
          protocol: UDP
          name: syslog
        - containerPort: 8181
          protocol: TCP
          name: http
        - containerPort: 8201
          protocol: TCP
          name: karaf
        volumeMounts:
        - name: config
          mountPath: /opt/minion/minion-config.yaml
          subPath: minion-config.yaml
        - name: jks
          mountPath: /opt/minion/etc/kafka-truststore.jks
          subPath: kafka-truststore.jks
      volumes:
      - name: config
        configMap:
          name: minion-config
      - name: jks
        configMap:
          name: kafka-certs
